# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: ibouabda <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/07/19 12:16:30 by ibouabda          #+#    #+#              #
#    Updated: 2018/07/25 16:57:39 by ibouabda         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = do-op

SRC = doop.c ft.c put.c

all: $(NAME)
$(NAME):
	gcc $(SRC) -o $(NAME)

clean:
	/bin/rm -f $(NAME)

fclean:clean

re: fclean all
